project_id = "tnhbijlskoffgoocftfq"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.approve-payment-demo]
verify_jwt = false

[functions.mercadopago-oauth-callback]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false