project_id = "tnhbijlskoffgoocftfq"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-oauth-callback]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.process-card-payment]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.subscription-webhook]
verify_jwt = false

[functions.cleanup-archived-pedidos]
verify_jwt = false

[functions.create-manual-subscription]
verify_jwt = false